/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShowStoriesIndexRouteImport } from './routes/show-stories/index'
import { Route as NewStoriesIndexRouteImport } from './routes/new-stories/index'
import { Route as JobStoriesIndexRouteImport } from './routes/job-stories/index'
import { Route as BestStoriesIndexRouteImport } from './routes/best-stories/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowStoriesIndexRoute = ShowStoriesIndexRouteImport.update({
  id: '/show-stories/',
  path: '/show-stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewStoriesIndexRoute = NewStoriesIndexRouteImport.update({
  id: '/new-stories/',
  path: '/new-stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobStoriesIndexRoute = JobStoriesIndexRouteImport.update({
  id: '/job-stories/',
  path: '/job-stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const BestStoriesIndexRoute = BestStoriesIndexRouteImport.update({
  id: '/best-stories/',
  path: '/best-stories/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/best-stories': typeof BestStoriesIndexRoute
  '/job-stories': typeof JobStoriesIndexRoute
  '/new-stories': typeof NewStoriesIndexRoute
  '/show-stories': typeof ShowStoriesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/best-stories': typeof BestStoriesIndexRoute
  '/job-stories': typeof JobStoriesIndexRoute
  '/new-stories': typeof NewStoriesIndexRoute
  '/show-stories': typeof ShowStoriesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/best-stories/': typeof BestStoriesIndexRoute
  '/job-stories/': typeof JobStoriesIndexRoute
  '/new-stories/': typeof NewStoriesIndexRoute
  '/show-stories/': typeof ShowStoriesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/best-stories'
    | '/job-stories'
    | '/new-stories'
    | '/show-stories'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/best-stories' | '/job-stories' | '/new-stories' | '/show-stories'
  id:
    | '__root__'
    | '/'
    | '/best-stories/'
    | '/job-stories/'
    | '/new-stories/'
    | '/show-stories/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BestStoriesIndexRoute: typeof BestStoriesIndexRoute
  JobStoriesIndexRoute: typeof JobStoriesIndexRoute
  NewStoriesIndexRoute: typeof NewStoriesIndexRoute
  ShowStoriesIndexRoute: typeof ShowStoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/show-stories/': {
      id: '/show-stories/'
      path: '/show-stories'
      fullPath: '/show-stories'
      preLoaderRoute: typeof ShowStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-stories/': {
      id: '/new-stories/'
      path: '/new-stories'
      fullPath: '/new-stories'
      preLoaderRoute: typeof NewStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/job-stories/': {
      id: '/job-stories/'
      path: '/job-stories'
      fullPath: '/job-stories'
      preLoaderRoute: typeof JobStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-stories/': {
      id: '/best-stories/'
      path: '/best-stories'
      fullPath: '/best-stories'
      preLoaderRoute: typeof BestStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BestStoriesIndexRoute: BestStoriesIndexRoute,
  JobStoriesIndexRoute: JobStoriesIndexRoute,
  NewStoriesIndexRoute: NewStoriesIndexRoute,
  ShowStoriesIndexRoute: ShowStoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
